In [1]:
import sklearn.naive_bayes
import pandas

In [15]:
l_emails=[1]*10+[0]*2390

In [16]:
spammy=[1]*9+ [0]+[0]*1799+[1]*591

In [17]:
df =pandas.DataFrame(data={'contains_legitimate_transaction':l_emails, 'is_spam':spammy})

In [18]:
classifier =sklearn.naive_bayes.GaussianNB()

In [19]:
classifier.fit(df[['contains_legitimate_transaction']],df.is_spam)

GaussianNB()

In [20]:
classifier.predict_proba([1])

C:\Users\jhuang\ANACONDA\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([[ 0.,  1.]])

In [21]:
classifier.predict([1])

C:\Users\jhuang\ANACONDA\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([1], dtype=int64)

In [22]:
classifier.score(df[['contains_legitimate_transaction']],df.is_spam)

0.7533333333333333

In [23]:
df['unclaimed'] = [0]*2399+[1]

In [24]:
df.tail()

contains_legitimate_transaction  is_spam  unclaimed
2395                                0        1          0
2396                                0        1          0
2397                                0        1          0
2398                                0        1          0
2399                                0        1          1

In [25]:
classifier.fit(df[['contains_legitimate_transaction','unclaimed']], df.is_spam)

GaussianNB()

In [26]:
classifier.predict([[0,1]])

array([1], dtype=int64)

In [27]:
classifier.predict_proba([[0,1]])

array([[ 0.,  1.]])

In [28]:
df['the']=[1]*2400

In [29]:
classifier.fit(df[['contains_legitimate_transaction','unclaimed','the']], df.is_spam)

GaussianNB()

In [30]:
classifier.predict([[0,0,1]])

array([0], dtype=int64)

In [31]:
classifier.predict_proba([[1,0,1]])

array([[ 0.,  1.]])